baseurl = "https://example.org/"
languageCode = "en-us"
title = "Origheart"
theme = "hugo-strata-theme"
disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Origheart"
	description = "ä¸ªäººåšå®¢ï¼Œåˆ†äº«ç¾å¥½çš„äº‹ç‰©å’ŒæŠ€æœ¯"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "avatar.jpg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "**I'm Origheart**<br>ä¸€ä½iOSå¼€å‘è€…ï¼Œå–œæ¬¢Swiftï¼Œæ­£åœ¨å­¦ä¹ Pythonã€‚ç°å°±èŒäº[51offer](//51offer.com)."
		# The icons will be shown if you enter your username
		twitter = "lk972105"
		github = "origheart"
		dribbble = ""
		facebook = ""
		googleplus = ""
		flickr = ""
		linkedin = ""

		copyright = [
			"&copy; Origheart"
			# "Design: [HTML5 UP](//html5up.net)",
			# "Demo Images: [Unsplash](//unsplash.com/)"
		]


	[params.about]
		hide  = false
		title = "æˆ‘å°†åœ¨è¿™é‡Œåšä»€ä¹ˆ"
		content = "1. åˆ†äº«è‡ªå·±çš„ä¸€äº›ç¼–ç¨‹ç»éªŒï¼Œå¹¶ä¸å¤§å®¶äº¤æµ \n2. æ— èŠæ—¶åœ¨è¿™å„¿æ‰“å‘æ—¶é—´ï¼Œè®°å½•è‡ªå·±ç”Ÿæ´»ä¸­çš„é‚£äº›å¼€å¿ƒä¸ä¸å¼€å¿ƒçš„äº‹å„¿\n3. ä»‹ç»è‡ªå·±åšè¿‡çš„ä¸€äº›é¡¹ç›®\n4. åˆ†äº«iOSå¼€å‘çš„æŠ€æœ¯å’Œå„ç§å‘"


	[params.portfolio]
		hide  = false
		title = "åˆ›æ„å®ç°"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "fulls/01.jpg"
			thumb = "thumbs/01.jpg"
			title = "æ¸…æ™¨çš„è¡—é“"
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/02.jpg"
			thumb = "thumbs/02.jpg"
			title = "[è¿½çˆ±è¡ŒåŠ¨](//)"
			description = "æ•™ä½ å¦‚ä½•è¿½ç”·/å¥³æœ‹å‹ğŸ˜„"

		[[params.portfolio.gallery]]
			image = "fulls/03.jpg"
			thumb = "thumbs/03.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/04.jpg"
			thumb = "thumbs/04.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/05.jpg"
			thumb = "thumbs/05.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/06.jpg"
			thumb = "thumbs/06.jpg"
			title = "å±±ä¸­çš„å°å±‹"
			description = "Lorem ipsum dolor sit amet."

	[params.recentposts]
		hide  = false
		title = "æœ€è¿‘çš„åšå®¢"

	[params.contact]
		hide  = false
		title = "å–å¾—è”ç³»"
		content = "æ¬¢è¿å¤§å®¶ä¸æˆ‘äº¤æµæŠ€æœ¯ã€ç”Ÿæ´»ã€æ‘„å½±ç­‰"

		address = [
			"2577åˆ›æ„å¤§é™¢",
			"é¾™åè·¯2577å·",
			"å¾æ±‡åŒº"
		]
		phone = "156-xxxx-7512"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "origheart@gmail.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"


# Menu links that appear on the left sidebar
[[menu.main]]
	name = "Home"
	url  = "/"
	weight = 0

[[menu.main]]
	name = "Blog"
	url  = "post/"
	weight = 10
